spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  rabbitmq:
    addresses:
    queue:

server:
  port: 8081
