spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    queue: ${RABBITMQ_QUEUE}

#server:
#  port: 8081
